<a href="https://colab.research.google.com/github/george-studenko/100_Days_of_ML_Code/blob/master/code/Celsius_to_Fahrenheit_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torch import optim

𝑓=𝑐×1.8+32

In [0]:
celsius    = np.array([[-40], [-10],  [0],  [8], [15], [22],  [38]],  dtype=float)
fahrenheit = np.array([[-40],  [14], [32], [46.4], [59], [71.6], [100.4]],  dtype=float)

test_set = np.array([[71],  [94], [117]],  dtype=float)
test_set_result_should_be = np.array([[159.8],  [201.2], [242.6]],  dtype=float)


In [0]:
celsius = Variable(torch.from_numpy(celsius))
fahrenheit = Variable(torch.from_numpy(fahrenheit))

test_set = Variable(torch.from_numpy(test_set))
test_set_result_should_be = Variable(torch.from_numpy(test_set_result_should_be))

In [131]:
celsius[0]

tensor([-40.], dtype=torch.float64)

In [0]:
linear_model = nn.Linear(1,1)

In [146]:
linear_model

Linear(in_features=1, out_features=1, bias=True)

In [147]:
linear_model.weight

Parameter containing:
tensor([[-0.4284]], requires_grad=True)

In [148]:
linear_model.bias

Parameter containing:
tensor([0.1566], requires_grad=True)

In [0]:
linear_model.double()
y = linear_model(celsius[0])

In [150]:
y

tensor([17.2945], dtype=torch.float64, grad_fn=<AddBackward0>)

In [0]:
criterion = nn.MSELoss()
sgd_optimizer = optim.SGD(linear_model.parameters(),lr = 0.001)

In [152]:
epochs = 600
print_every = 50
steps = 0

for epoch in range(epochs):
    running_loss = 0
    
    linear_model.train()
    
    # train
    for index in range(len(celsius)):
        steps += 1
        
        # Set gradients to zero
        sgd_optimizer.zero_grad()
        
        y_hat = linear_model.forward(celsius[index])
        loss = criterion(y_hat,fahrenheit[index])
        loss.backward()
        sgd_optimizer.step()
        
        running_loss += loss.item()
        
        if steps % print_every == 0:
            linear_model.eval()
          #  with torch.no_grad():
          #      test_loss, accuracy = validation(linear_model,testloader,criterion)
            
            print("Epoch: {}/{}... ".format(epoch+1, epochs),
                  "Loss: {:.3f}".format(running_loss/print_every))
                 # "Test Loss: {:.3f}".format(test_loss/len(testloader)),
                 # "Test Accuracy: {:.3f}".format(accuracy/len(testloader)))
            
            running_loss = 0
            
            linear_model.train()

Epoch: 8/600...  Loss: 8.683
Epoch: 15/600...  Loss: 9.436
Epoch: 22/600...  Loss: 20.998
Epoch: 29/600...  Loss: 45.084
Epoch: 36/600...  Loss: 65.423
Epoch: 43/600...  Loss: 62.429
Epoch: 50/600...  Loss: 56.593
Epoch: 58/600...  Loss: 2.862
Epoch: 65/600...  Loss: 3.110
Epoch: 72/600...  Loss: 6.920
Epoch: 79/600...  Loss: 14.858
Epoch: 86/600...  Loss: 21.560
Epoch: 93/600...  Loss: 20.574
Epoch: 100/600...  Loss: 18.651
Epoch: 108/600...  Loss: 0.943
Epoch: 115/600...  Loss: 1.025
Epoch: 122/600...  Loss: 2.281
Epoch: 129/600...  Loss: 4.896
Epoch: 136/600...  Loss: 7.105
Epoch: 143/600...  Loss: 6.780
Epoch: 150/600...  Loss: 6.146
Epoch: 158/600...  Loss: 0.311
Epoch: 165/600...  Loss: 0.338
Epoch: 172/600...  Loss: 0.752
Epoch: 179/600...  Loss: 1.614
Epoch: 186/600...  Loss: 2.342
Epoch: 193/600...  Loss: 2.234
Epoch: 200/600...  Loss: 2.026
Epoch: 208/600...  Loss: 0.102
Epoch: 215/600...  Loss: 0.111
Epoch: 222/600...  Loss: 0.248
Epoch: 229/600...  Loss: 0.532
Epoch: 236/60

In [166]:
linear_model.weight.item()

1.7996913422235987

In [167]:
linear_model.bias.item()

31.958804349211995

In [0]:
def run_tests():
  for index in range(len(test_set)):
    prediction = linear_model(test_set[index])
    label = test_set_result_should_be[index]
    print(f'Prediction:{prediction.item()} Label: {label.item()}')

In [165]:
run_tests()

Prediction:159.7368896470875 Label: 159.8
Prediction:201.12979051823027 Label: 201.2
Prediction:242.52269138937305 Label: 242.6
